name: Destroy Terraform and Packer AWS Automation 

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Resources to be destroyed'
        required: false
        

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARGS: "-av"

jobs:
   packer_terraform_destroy:
    name: 'packer_terraform_destroy'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: './scripts'
      TF_TERRAFORM_DIR: './terraform-deploy'
      TF_TERRAFORM_BUCKET_DIR: './terraform-bucket'
      TF_PACKER_DIR: './packer'
      TF_PACKER_CONFIG_FILE: 'aws_packer_ami.pkr.hcl'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Install dependencies python
        run: |
          python -m pip install --upgrade pip
          pip install awscli        
      - name: Install Jq
        id: jq_install
        run: |
            mkdir -p ${HOME}/.local/bin
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O ${HOME}/.local/bin/jq
            chmod +x ${HOME}/.local/bin/jq
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
        shell: bash 

      - name: Terraform deploy Init
        id: init_deploy
        run: |
          cd ../${{ env.TF_TERRAFORM_DIR }}
          terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" \
            -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}" \
            -input=false -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform deploy Destroy
        run: |
          cd ../${{ env.TF_TERRAFORM_DIR }}
          terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   

      # - name: Init script packer-terraform.sh
      #   id: init_script
      #   run: |
      #       chmod +x packer-terraform.sh 
      #       ./packer-terraform.sh destroy
      #   shell: bash

      - name: Destroy AMI and Snapshots
        id: destroy_ami
        run: |
          aws s3 cp s3://packer-manifest/packer-manifest/packer_manifest.json ../${{ env.TF_PACKER_DIR }}
          AMI_ID=$(jq -r '.builds[-1].artifact_id' ../${{env.TF_PACKER_DIR}}/packer_manifest.json | cut -d ":" -f2)
          Snap=$(aws ec2 describe-images --image-ids $AMI_ID --region eu-west-2 --query 'Images[*].BlockDeviceMappings[*].Ebs.SnapshotId' --output text)
          for SNAPSHOT in $Snap; do echo $SNAPSHOT; done
          aws ec2 deregister-image --image-id $AMI_ID --region eu-west-2
          for SNAPSHOT in $Snap; do aws ec2 delete-snapshot --region eu-west-2 --snapshot-id $SNAPSHOT; done
        shell: bash

      - name: Terraform bucket Init
        id: init_bucket
        run: |
          cd ../${{ env.TF_TERRAFORM_BUCKET_DIR }}
          terraform init -backend-config="access_key=${AWS_ACCESS_KEY_ID}" \
            -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}" \
            -input=false -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform bucket Destroy
        run: |
          cd ../${{ env.TF_TERRAFORM_BUCKET_DIR }}
          terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   